"""
Advisory Service — RAG-powered
--------------------------------
Fully replaces the old static/fallback implementation.
All answers are generated by the Groq LLM using retrieved
context from the advisory knowledge base. No pre-computed
results are returned.
"""

import logging
from langchain.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.runnables import RunnablePassthrough

from app.schemas.advisory import AdvisoryRequest, AdvisoryResponse
from app.core.rag_engine import RAGEngine

logger = logging.getLogger(__name__)


class AdvisoryService:
    def __init__(self, engine: RAGEngine):
        self._retriever = engine.get_retriever("advisory")
        self._llm = engine.get_llm()
        self._parser = JsonOutputParser(pydantic_object=AdvisoryResponse)

        self._prompt = PromptTemplate(
            template=(
                "You are an expert business advisory engine specializing in Indian MSMEs and startups.\n"
                "Use ONLY the retrieved context below to generate a thorough, actionable analysis.\n"
                "Respond STRICTLY in the JSON format described by the format instructions.\n\n"
                "{format_instructions}\n\n"
                "=== Retrieved Context ===\n"
                "{context}\n\n"
                "=== Business Details ===\n"
                "Business Type      : {business_type}\n"
                "Location           : {location}\n"
                "Target Audience    : {target_audience}\n"
                "Unique Selling Proposition (USP): {unique_selling_proposition}\n\n"
                "CRITICAL: Your JSON response MUST include ALL of the following keys:\n"
                "  1. market_reach       — Specific, quantified estimate of potential customer base.\n"
                "  2. opportunities      — List of at least 4 concrete, actionable growth opportunities.\n"
                "  3. swot_analysis      — Object with keys 'strengths', 'weaknesses', 'opportunities', 'threats',\n"
                "                          each being a list of at least 3 items.\n"
                "  4. pricing_strategy   — Recommended pricing approach with justification.\n"
                "  5. competitor_analysis — Key competitors and differentiation tactics.\n"
                "Omitting any key is NOT allowed. Return ONLY valid JSON. No markdown, no text outside the JSON.\n"
            ),
            input_variables=[
                "context",
                "business_type",
                "location",
                "target_audience",
                "unique_selling_proposition",
            ],
            partial_variables={"format_instructions": self._parser.get_format_instructions()},
        )

        self._chain = (
            RunnablePassthrough.assign(
                context=lambda x: self._retrieve_context(x)
            )
            | self._prompt
            | self._llm
            | self._parser
        )

    def _retrieve_context(self, inputs: dict) -> str:
        query = (
            f"{inputs['business_type']} business in {inputs['location']} "
            f"targeting {inputs['target_audience']} with USP: {inputs['unique_selling_proposition']}"
        )
        docs = self._retriever.invoke(query)
        return "\n\n".join(doc.page_content for doc in docs)

    def analyze(self, request: AdvisoryRequest) -> AdvisoryResponse:
        logger.info(
            "Advisory RAG: analyzing business_type=%s location=%s",
            request.business_type,
            request.location,
        )
        result = self._chain.invoke({
            "business_type": request.business_type,
            "location": request.location,
            "target_audience": request.target_audience,
            "unique_selling_proposition": request.unique_selling_proposition,
        })
        return AdvisoryResponse(**result)
